apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: golang
  labels:
    app: go-app
spec:
  selector:
    app: go-app
  type: NodePort
  ports:
    - protocol: TCP
      #system port 
      port: 80
    # port on which application is runnign
      targetPort: 8080
    # port on which we are routing the traffic
      nodePort: 30009
