apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: golang
spec:
  selector:
    app: go-app
  # commneted nodeport as goal is to is to use ingress
  # usingg cluster ip to ensure that svc is accesable internally but using ingress traffic is
# still forwareded to svc , ingress is just advanced version of routing traffic . 
  type: ClusterIP
  ports:
    - protocol: TCP
      #system port 
      port: 80
    # removed target port and nodeport as goal is to implement using ingress svc here 
      targetPort: 8080
